### ISSUE TITLE
根据Runtime教程运行后报错

### ISSUE THREAD

**Issue by CarryKiana** [Tencent/tmagic-editor#157]
根据https://tencent.github.io/tmagic-editor/docs/tutorial/runtime.html教程搭建项目，runtime项目以打包产物的形式放入editor项目的public文件夹下，正常运行后，添加组件成功，但有以下现象：
1、新建页面后，滚动鼠标滚轮，报错：
Uncaught Error: page 未初始化
    at StageMask.mouseWheelHandler (StageMask.ts:324:27)
2、焦点在页面的情况下，拖动，报错：
Uncaught (in promise) Error: 没有配置或者配置缺少id值
    at Editor$1.update (editor.ts:391:28)
    at dispatch (compose.ts:27:32)
    at compose.ts:19:12
    at doAction (BaseService.ts:53:34)
    at BaseService.ts:147:37
    at Editor$1.doTask (BaseService.ts:181:13)
    at Editor$1.value (BaseService.ts:156:18)
    at Editor$1.sort (editor.ts:464:16)
    at dispatch (compose.ts:27:32)
    at compose.ts:19:12
3、修改组件高度，能改变并且反馈到右侧样式面板，反之，没有反应
4、组件依旧如教程helloworld一般，不能拖动

**Comment by CarryKiana** [comment]
问题1解决，参考playground代码，runtime更新回传dom给editor没传到位，iframe调试有点麻烦

**Comment by jia000** [comment]
runtime教程里的代码并没有实现完整的功能，拖动是会有问题的，原因是没有完整的解析style，这个会在后面的教程继续完善说明清楚
