### ISSUE TITLE
关于ant-design-vue问题

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#446]
你好，请问下，
目前我在ui跟playground中使用了ant-design-vue，然后我在根目录下执行build:runtime:admin的时候rollup-plugin-external-globals报错了，具体错误：
 [rollup-plugin-external-globals] Unexpected token (16:6)
│ file: F:/vdo/vdo-lowcode/node_modules/.pnpm/ant-design-vue@3.2.13_vue@3.2.39/node_modules/ant-design-vue/dist/antd.css:16:6
│ error during build:
│ SyntaxError: Unexpected token (16:6)
│     at Parser.pp$4.raise (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:19614:13)
│     at Parser.pp$9.unexpected (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:16908:8)
│     at Parser.pp$9.expect (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:16902:26)
│     at Parser.pp$8.parseClass (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:17537:8)
│     at Parser.pp$5.parseExprAtom (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:18973:17)
│     at Parser.pp$5.parseExprSubscripts (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:18781:19)
│     at Parser.pp$5.parseMaybeUnary (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:18747:17)
│     at Parser.pp$5.parseExprOps (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:18674:19)
│     at Parser.pp$5.parseMaybeConditional (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:18657:19)
│     at Parser.pp$5.parseMaybeAssign (file:///F:/vdo/vdo-lowcode/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:18624:19)

**Comment by jia000** [comment]
这里是想用ant-design-vue来做什么，业务组件吗？

**Comment by Carloslst** [comment]
> 这里是想用ant-design-vue来做什么，业务组件吗？

ui里面我用的是ant-design-vue来做的一些基础组件和一些业务组件

**Comment by Frankiness** [comment]
> 

你好，我也遇到了这个问题，请问怎么能解决呢？

**Comment by Frankiness** [comment]
去掉 main.ts 文件引用的 antd.css 中的注释即可
