### ISSUE TITLE
tmagic-admin server端运行  yarn dev src/controller/act.ts:30:46 - error TS18046: 'ctx.request.body' is of type 'unknown'.

### ISSUE THREAD

**Issue by m13811126663** [Tencent/tmagic-editor#459]
平台：window11
node版本：v14.21.1
tmagic-admin server端运行  yarn dev
出现错误 src/controller/act.ts:30:46 - error TS18046: 'ctx.request.body' is of type 'unknown'.

D:\newlive\tmagic\magic-admin\server\node_modules\ts-node\src\index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/controller/act.ts:30:63 - error TS2339: Property 'data' does not exist on type 'unknown'.

30       const query: ActListQuery = JSON.parse(ctx.request.body.data);
                                                                 ~~~~
src/controller/act.ts:52:66 - error TS2339: Property 'data' does not exist on type 'unknown'.

52       const actInfo: ActInfoDetail = JSON.parse(ctx.request.body.data);
                                                                    ~~~~
src/controller/act.ts:70:62 - error TS2339: Property 'data' does not exist on type 'unknown'.

70       const copyInfo: CopyInfo = JSON.parse(ctx.request.body.data);
                                                                ~~~~
src/controller/act.ts:105:54 - error TS2339: Property 'data' does not exist on type 'unknown'.

105       const { pageId } = JSON.parse(ctx.request.body.data);
                                                         ~~~~

    at createTSError (D:\newlive\tmagic\magic-admin\server\node_modules\ts-node\src\index.ts:434:12)
    at reportTSError (D:\newlive\tmagic\magic-admin\server\node_modules\ts-node\src\index.ts:438:19)
    at getOutput (D:\newlive\tmagic\magic-admin\server\node_modules\ts-node\src\index.ts:578:36)
    at Object.compile (D:\newlive\tmagic\magic-admin\server\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (D:\newlive\tmagic\magic-admin\server\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (D:\newlive\tmagic\magic-admin\server\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jia000** [comment]
请检查typescript/ts-node版本，tsconfig配置
