### ISSUE TITLE
初始化安装依赖运行 pnpm run bootstrap 报错 windows  node 16.11.0

### ISSUE THREAD

**Issue by jzfai** [Tencent/tmagic-editor#556]
pnpm: depNode.fetchingFiles is not a function
    at D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:130469:45
    at Array.map (<anonymous>)
    at linkAllPkgs (D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:130468:35)
    at linkNewPackages (D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:130435:9)
    at async linkPackages (D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:130289:27)
    at async _installInContext (D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:131134:25)
    at async installInContext (D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:131374:16)
    at async _install (D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:130924:25)
    at async mutateModules (D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:130694:23)
    at async recursive (D:\nodejs\v16\node_modules\pnpm\dist\pnpm.cjs:131972:29)
Progress: resolved 1090, reused 1044, downloaded 0, added 0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by jia000** [comment]
pnpm 版本是多少，请确保是最新版本

确保node版本是 v16.14以上，可以换成node 18试试
