### ISSUE TITLE
本地调试 magic admin server 提示 Unable to compile TypeScript

### ISSUE THREAD

**Issue by yuzuofu** [Tencent/tmagic-editor#78]
前置操作：
1. 修改 db 配置
2. npm i 安装依赖
3. npm run dev

报错信息：
> magic-admin@1.0.0 dev
> nodemon

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node -r tsconfig-paths/register src/index.ts --files`

/Users/yuzf/walle/tmagic-editor/magic-admin/server/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:26:9 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.

26 const { PORT } = process.env;
           ~~~~

    at createTSError (/Users/yuzf/walle/tmagic-editor/magic-admin/server/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/Users/yuzf/walle/tmagic-editor/magic-admin/server/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/Users/yuzf/walle/tmagic-editor/magic-admin/server/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/Users/yuzf/walle/tmagic-editor/magic-admin/server/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/Users/yuzf/walle/tmagic-editor/magic-admin/server/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/yuzf/walle/tmagic-editor/magic-admin/server/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

node 版本：v16.15.0
npm 版本：8.5.5
操作系统：Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

**Comment by unique-vv** [comment]
安装tslib
`npm i tslib`
magic-admin\server\tsconfig.json加上
`{
  "compilerOptions": {
"paths": {
"tslib": [
				"node_modules/tslib/tslid.d.ts"
			]
`

**Comment by khuntoriia** [comment]
请尝试使用node14版本安装依赖并运行
